### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by faridmd** [Fluxticks/TikTokDL#5]
I can run the module on windows 11 but i can't run on ubuntu 20.04

Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tiktokdl.download_post import get_post
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/supernova/.local/lib/python3.8/site-packages/tiktokdl/download_post.py", line 10, in <module>
    from tiktokdl.captcha import handle_captcha
  File "/home/supernova/.local/lib/python3.8/site-packages/tiktokdl/captcha.py", line 9, in <module>
    from tiktokdl.image_processing import find_position, image_from_url
  File "/home/supernova/.local/lib/python3.8/site-packages/tiktokdl/image_processing.py", line 46, in <module>
    def find_position(background_image: Mat, piece_image: Mat, method: int = cv.TM_SQDIFF) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable
>>>

**Comment by Fluxticks** [comment]
Currently due to the type-hinting I've used the minimum python version supported is 3.10.* . If I get time I can refactor the type hinting to support earlier versions of python.

**Comment by Fluxticks** [comment]
Implemented in [v1.5.2](https://github.com/Fluxticks/TikTokDL/releases/tag/v1.5.2)
